### ISSUE TITLE
Change the website name from 'Klimaat Helpdesk' to 'KlimaatHelpdesk'

### ISSUE THREAD

**Issue by daanreijnders** [Klimaat-Helpdesk/website#40]
A new styling of the name 'KlimaatHelpdesk' has been agreed upon. Can the website name be changed to this? I had a look at the code myself, but don't have experience with Django/Wagtail, so I don't know where the name is set.

**Comment by aquilesC** [comment]
Hello Dan! 

For documentation purposes, could you point to where the agreement has been discussed? 

To find the relevant pieces of code, you can use the search within the repository, and filter by the relevant file types. Since you want to change something on the Template, you have to filter by HTML, take a look at this link:

https://github.com/Klimaat-Helpdesk/website/search?l=HTML&q=Klimaat+Helpdesk

And in there you find the ``base.html`` file that has the ``<title>`` defined with the ``Klimaat Helpdesk``. You are very welcome to change the code and create a pull request.

**Comment by daanreijnders** [comment]
@SanliFaez Could you point to the minutes of the meeting where this was decided? I wasn't there myself. I'll file the PR after that.

**Comment by SanliFaez** [comment]
there was no official meeting, but an email conversation between several people including those who check the info mailbox. One of the first emails we received on info was saying that grammatically klimaathelpdesk is one word in dutch. Other people had mentioned this also in the past, and this became a repeated discussion that we needed to act upon. 
we choose for KlimaatHelpdesk to help with readability. Not exactly a correct dictation, but at least it is a clearly deliberate choice.

**Comment by aquilesC** [comment]
Thanks @SanliFaez ! 

Is this something that appears anywhere else besides the title of the page? If not, I will just merge #46 and close this issue.

**Comment by daanreijnders** [comment]
From the search query in the repo, it seems to be only the title. Are titles of sub-pages generated through the title in `base.html`?

**Comment by aquilesC** [comment]
Yes, all the titles are the same, that is why I also opened #47 so we can improve on that. 

I'll take care of this issue later today or tomorrow.
