### ISSUE TITLE
error

### ISSUE THREAD

**Issue by huberma** [Klimaat-Helpdesk/website#78]
Browser: Chrome, operating system: 

![Screenshot from 2021-01-27 13-00-47](https://user-images.githubusercontent.com/41013055/105988300-b785d500-609f-11eb-925e-df8c88596eed.png)

**Comment by aquilesC** [comment]
Ohh, it came back! This problem was known when Fabrique worked on the website and I thought it was solved. Do you also see it on mobile? (Or was this mobile?)

**Comment by huberma** [comment]
No, with a quick check with the people in the meeting, noone had it on the mobile

**Comment by aquilesC** [comment]
I have just tried with Chrome and I can't see it. I know this was a problem in the past and Fabrique solved it. I really wonder why it appears to you. Could you try to do a hard refresh just to be sure it's not due to a cached version?
 
- If you are on Windows, press Ctrl+F5 while on the klimaat website. 
- On Mac it is CMD + Shift + R

And then let me know if it is still there.

**Comment by aquilesC** [comment]
Nevermind, found the problem. Somehow a non-valid character slipped through. Fixing it now.
