### ISSUE TITLE
quick-hack for showing accepted questions

### ISSUE THREAD

**Issue by SanliFaez** [Klimaat-Helpdesk/website#82]
There is a suggestion by the editorial team to show accepted questions that are in the editorial process on the website. One quick way is to add a new category "wordt beantwoord" and just add the new questions we send to expert without an answer field. 
This however requires a couple of fixes because with the current setting they will dominate the front page.

1- Can we exclude this specific category from being shown on the front page?
2- Can we easily add a page that queries only these questions and link to it somewhere in the new question form?

this is not a concrete issue but just to initiate the idea of of handling this request before v2. What do you think @aquilesC ?

**Comment by aquilesC** [comment]
It can be done. Regarding 1, that was a feature that was later abandoned (see #43 ). So I would avoid it. 

If the order of the questions is not important, I can do it quickly (i.e. display a list of the open questions). I would just need: where to put the link to this new page, with what text, its url (e.g. /what). 

Questions will be picked up automatically from the questions module on the CMS. Since answered questions are still there, they won't be filtered out. It may be worth cleaning up the list of questions while I implement this new page).

**Comment by Arfor** [comment]
I would create a new entry in the menu which links to the new page with open questions.
The new page could be /vraag_in_behandeling/, but what can we put in the menu which is shorter? Open vragen sounds as if they can't be answered.
Maybe we can call it the "Vragenbak" and rename "Jullie vragen" -> "Beantwoorde vragen"?

@daanreijnders @JoselineHouwman, what do you think?

**Comment by daanreijnders** [comment]
Maybe simply "in behandeling"? I think it's implied that we'd mean questions by that. "Vragenbak" is a little more ambiguous; it doesn't necessarily mean unanswered.

**Comment by aquilesC** [comment]
Thanks to @Arfor for pointing it out, this issue is related to #54 , which means there's no *quick* hack as I thought there would be. I should spend a couple of hours first solving #54 and then looking into this. In the mean time, would be great to know how do you foresee the questions being displayed. I was going for exactly this style, without links, and adding the date (instead of the author):

<img width="868" alt="Screenshot 2021-02-16 at 13 44 02" src="https://user-images.githubusercontent.com/2494344/108064526-1adea380-705d-11eb-9329-f24ee8dc1e14.png">

**Comment by JoselineHouwman** [comment]
@daanreijnders I like the suggestion to name the new category "in behandeling". @aquilesC I would indeed follow the same style. I'm a bit hesitant to add the date, as we're not the fastest with actually answering the questions, but on the other hand it might be a good stick to get us working faster ;).  

Another thing is the question whether we want the questions picked automatically from the cms, as we often have to reformulate questions. Or has that become obselete Aquiles as there is no quick hack?

**Comment by aquilesC** [comment]
@JoselineHouwman I will have to check what other things depend on the question itself to decide if it is a matter of hours or days to make a change. In any case, it would be good to have consensus on how to display the approved questions. What you mention of reformulating the questions is useful to know. Does this happen at the moment of approving the question or at a discussion-level on Gitlab?

**Comment by JoselineHouwman** [comment]
Depends a bit on the question and how "vague" it is. During the editors-in-chief meetings twice a week we check the new questions and whether they need reformulation. If it's a quick fix (or slight grammer/spelling mistakes) we immediately implement them. If a question is more imprecise or vague we ask in the Teams editor channel how we should reformulate or we ask the questionee for extra clarificiation. If they left an email address we always send an email with the new formulation and ask whether they agree. 
So I think it would probably make the most sense to display those questions that have been reformulated and/or of which the questionee aproves

**Comment by Arfor** [comment]
For the vague questions we can indeed decide to leave them in limbo until we decide on a reformulation and have the approval of the vraagsteller.

The ideal scenario would be if we can change the question field separately from the extra info in the CMS before approval and that the question field is then used to create the entry on the "in behandeling" page, just like the answers page.

**Comment by aquilesC** [comment]
Would the following flow work? 

- Once a question is approved, a new 'Question In Progress' is created on the CMS. 
- This new question will not be visible until someone clicks 'make visible', giving the opportunity to edit, reformulate, etc. The advantage is that the original questions will stay, as a record. 
- Once the question gets an answer, someone manually removes it from the Question In Progress.

I think there is still quite a lot of manual upkeep that could be removed in later iterations of the website, and now questions would be duplicated which I think is not a good idea, but if not, there would be no 'quick fix'.

**Comment by SanliFaez** [comment]
I agree with this suggestion. just a few minor questions: 
- at which stage will the question in progress get a category?
- will they show up in the list existing questions in the form for asking a new question?
- where/how do we create a link to this page?

**Comment by aquilesC** [comment]
If it is a quick hack:

> will they show up in the list existing questions in the form for asking a new question?

The answer is no. I would not like to mess with the form's javascript, etc. 

> where/how do we create a link to this page?

I assumed from the sidebar and perhaps a link from the form to ask a question

> at which stage will the question in progress get a category?

This is for editors to think about, at which stage are categories assigned? Is it worth having the questions with explicit categories before knowing how the expert would tackle the issue? (Bear in mind there'll be no filtering, no pagination, etc. just a list of questions ordered chronologically, alphabetically, or with another criterium)

**Comment by Arfor** [comment]
Sounds good! It's indeed one more step in the process, but it's definitely worth the effort in my opinion.

I would leave out the categories on the in-progress list if we cannot filter on it. If we feel it would be much clearer with the filtering option, it could be added in a later iteration.

**Comment by aquilesC** [comment]
I have added some changes based on the discussion here, @Arfor (and the others), let me know what you think. I'll summarize here:

- Questions got separated fields for the text of the question, timespan, location, and extra info. Each can be edited separately on the CMS
- Questions got a new field called "Status" which can be Undecided, Approved, Answered, Rejected
- Questions marked as approved show up in: [https://klimaathelpdesk.org/in_progress](https://www.klimaathelpdesk.org/in_progress)
- With these changes, the messages on the Gitlab repository should also be clearer than before

What **I am missing is**: 
The URL in which to display the questions in progress, and how to link to it (the text). And if there should be any info before/after the list of questions.

**Comment by Arfor** [comment]
This looks great Aquiles, thanks! I'll try to go through the list asap and assign the status so that the "approved" checkbox can be removed.

- As for the URL, I think we decided on "in_behandeling", which would then also be the entry in the sidebar menu.
- A small change to the text on top of the page _Jullie recente vragen_ -> _Op dit moment zijn de volgende vragen in behandeling:_
- I don't think more info is needed, but if we'd want more explanation, the text on top of  the /ask page could be applicable here.
- You said we cannot filter on the categories on the /in_behandeling page itself, so I suppose it is also not possible to have them show up when you click a category on the /ask page? If not, that would be a great addition to future versions.
- It might be nice to add a button to link to "in behandeling" in the bottom right as well and changing the text _Stel je eigen vraag!_ -> _Check de vragen in behandeling of stel je eigen vraag!_ 
![afbeelding](https://user-images.githubusercontent.com/37039019/110306626-50dccb00-7ffe-11eb-810f-def492ff05c5.png)

**Comment by aquilesC** [comment]
I'll changie the URL and text later today. 

> - You said we cannot filter on the categories on the /in_behandeling page itself, so I suppose it is also not possible to have them show up when you click a category on the /ask page? If not, that would be a great addition to future versions. 

I am not showing the categories of the questions, but could do it in the same fashion that is done on the homepage (actually, had to remove that part of the code, because I thought it was not desired, perhaps my mistake). For filtering, I can copy what is currently done, but I must dig into extra parts of the code in which I am not as comfortoble, so it'll take longer (that's why it does not fall under the 'quickfix' approach). 

> - It might be nice to add a button to link to "in behandeling" in the bottom right as well and changing the text Stel je eigen vraag! -> Check de vragen in behandeling of stel je eigen vraag!

A button with the same style as the current stel je vraag? 

I was planning to add an extra link on the menu, what should the text be? If I use 'in behandeling', is it clear it means questions being answered?

**Comment by Arfor** [comment]
Yes you're right, since we're not always 100% sure if we assign the right category. Sometimes it depends on the answer as well. However, since one of the purposes of an in_progress list is that people know if a question is being handled, it makes sense to have it show up when you ask a question, which is very neatly done when you click a category in /ask. Sorry I didn't think of this before. 
Would it be possible to add the category right under the question and to remove the lower spacing (such that the vertical size doesn't change)? Something like this:
![afbeelding](https://user-images.githubusercontent.com/37039019/110319114-b638b800-800e-11eb-97be-118d7a7182fa.png)

Yep, the same button style would be perfect! And 'in behandeling' should indeed be clear enough.

Whilst changing the status of the older accepted questions, I found that quite a few have been reformulated. Could you add another field "original question"  in the CMS? Sometimes the original question hides some information in the way the person would like to see the answer, it'd be a shame to loose that.

**Comment by aquilesC** [comment]
@Arfor , I have implemented several of the things discussed, but not all. Please check the comments on #84 to understand what and why some things are missing. Filtering is not going to be easy given how things are right now and I would be hesitant about building more complexity on the question handling right now.

**Comment by aquilesC** [comment]
By the way, you should have faced some errors when trying to create a question from scratch, not edit an existing one (at least, it appears in the logs that you had problems), they should also be fixed now, could you try again?

**Comment by Arfor** [comment]
On the website it looks great! I had in my mind to add In Behandeling as an entry in the sidebar, but it looks much better as a button next to stel je vraag. 

All good, I can create a problem from scratch now, thanks!

Aah, I see the issue with the categories, that does complicate it quite a bit. For now we can always refer the vraagsteller to the in behandeling list.

**Comment by aquilesC** [comment]
If things are OK with this quick fix, we can close the issue and open individual issues for the missing things (like categories, styling, etc.). If you agree, just ago ahead and close it once the other issues are created, thanks!

**Comment by SanliFaez** [comment]
I have not much fruitful to add, but I want to express my gratitude and compliments before the issue is closed. It looks REALLY nice. Thank you!
